import { ThemePack } from '../types';

export const nordicTheme: ThemePack = {
  id: 'nordic',
  name: 'Vintage Voyager',
  description: 'Travel-inspired vintage design with passport aesthetics and aged paper textures',
  tokens: {
    background: '#f4ecd8',
    foreground: '#2c2825',
    card: '#f4ecd8',
    cardForeground: '#2c2825',
    primary: '#c24d3b',
    primaryForeground: '#FFFFFF',
    secondary: '#3b6c8a',
    secondaryForeground: '#FFFFFF',
    muted: '#e8dfc5',
    mutedForeground: '#5d5650',
    accent: '#c24d3b',
    accentForeground: '#FFFFFF',
    destructive: '#c24d3b',
    border: '#d1c7b0',
    input: '#f4ecd8',
    ring: '#c24d3b',
    chart1: '#c24d3b',
    chart2: '#3b6c8a',
    chart3: '#b58e46',
    chart4: '#8B7355',
    chart5: '#6B8E23',
    glow: 'rgba(194, 77, 59, 0.2)',
    gradientStart: '#c24d3b',
    gradientEnd: '#8B4E48',
    radius: '0.75rem',
  },
  motion: {
    pageTransition: {
      initial: { opacity: 0, y: 8 },
      animate: { opacity: 1, y: 0 },
      exit: { opacity: 0, y: -8 },
      transition: { duration: 0.3 },
    },
    cardHover: {
      y: -2,
      transition: { duration: 0.2, ease: 'easeOut' },
    },
    stagger: 0.05,
    duration: { fast: 0.2, normal: 0.3, slow: 0.5 },
    easing: [0.25, 0.1, 0.25, 1],
  },
  fonts: {
    heading: '"Playfair Display", serif',
    body: '"DM Sans", sans-serif',
    mono: '"Courier Prime", "Courier New", monospace',
  },
  background: {
    type: 'texture',
    config: {
      color: '#E8DCCA',
      texture: 'paper',
      overlay: 'url(https://www.transparenttextures.com/patterns/cream-paper.png)',
      opacity: 0.4,
    },
  },
  preview: {
    accent: '#B94E48',
    icon: '✈️',
  },
};
